version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7V2f9W8LqA83Eqr # Reemplaza con tu contraseña segura
      MYSQL_USER: upsSeguridad # Reemplaza con tu nombre de usuario
      MYSQL_PASSWORD: 7V2f9W8LqA83Eqr # Reemplaza con la contraseña para upsSeguridad
      MYSQL_DATABASE: virustotal
    ports:
      - "30001:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
