version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: virustotal
      POSTGRES_USER: upsSeguridad
      POSTGRES_PASSWORD: 7V2f9W8LqA83Eqr
    ports:
      - "30001:5432"
    volumes:
      - my-db:/var/lib/postgresql/data

volumes:
  my-db:
