import './global.css';
import { Box, Grid, Typography } from '@mui/material';
import SidebarMenu from './side-bar/side-bar';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Box sx={{ display: 'flex', height: '100vh', overflow: 'hidden' }}>
      <Box sx={{ display: 'flex', flexDirection: 'column', width: '100%' }}>
        <Box component="header" sx={{ width: '100%', p: 1 }}>
          <Typography variant="h1">Header</Typography>
        </Box>
        <Box
          component="main"
          sx={{
            flexGrow: 1,
            overflowY: 'auto',
            p: 1
          }}
        >
          {children}
        </Box>
        <Box component="footer" sx={{ width: '100%', p: 1 }}>
          <Typography variant="h1">Footer</Typography>
        </Box>
      </Box>
    </Box>
  );
}
