import './global.css';
import { Typography } from '@mui/material';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <>
      <header>
        <Typography variant={'h1'} >Header</Typography>
      </header>

      <main>
        {children}
      </main>

      <footer>
        <Typography variant={'h1'} >Footer</Typography>
      </footer>
    </>
  );
}
